os: windows
language: C++
env: PATH=/c/Python38:/c/Python38/Scripts:$PATH
before_install:
#  - choco install -y visualstudio2017buildtools
#  - choco install -y visualstudio2017-workload-vctools
  - choco install  python --version 3.8.0
  - python -m pip install --upgrade pip
  - python -m pip install aqtinstall
  - python -m aqt install --outputdir /c/Qt 5.14.2 windows desktop win32_msvc2017
script:
  - qmake -spec win32-g++ licensePlate.pro 
  - mkdir build
  - cd build
  - cmake -DCMAKE_PREFIX_PATH="C:\Qt\5.14.2\msvc2017" -DCMAKE_BUILD_TYPE=RELEASE -DDEPLOY_QT_LIBRARIES=ON ..
  - cmake --build .
  - cp *.qm ./Debug
  - 7z a -tzip editor.zip -r *
deploy:
  provider: releases
  skip_cleanup: true
  api_key: $GITHUB_TOKEN
  file: editor.zip
  on:
    tags: false
    draft: true
