# windows.yml
name: Windows
env: 
   ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
on:
  # push代码时触发workflow
  push:
    # 忽略README.md
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
  # pull_request时触发workflow
  pull_request:
    # 忽略README.md
    paths-ignore: read-all|write-all
permissions:
  pull-requests: write
  issues: write
  repository-projects: write
jobs:
  build:
    name: Build
    # 运行平台， windows-latest目前是windows server 2019
    runs-on: windows-latest
    strategy:
      # 矩阵配置
      matrix:
        qt_ver: [5.9.8]
        qt_target: [desktop]
        # mingw用不了
        # qt_arch: [win64_msvc2017_64, win32_msvc2017, win32_mingw53,win32_mingw73]
        qt_arch: [win64_msvc2017_64]
        # 从矩阵中除外的配置
        exclude: 
          # 不存在5.9.8-win32_msvc2017的版本
          - qt_ver: 5.9.8
            qt_arch: win32_msvc2017
          # mingw用不了
          # - qt_ver: 5.9.8
          #   qt_arch: win32_mingw73
          # - qt_ver: 5.12.6
          #   qt_arch: win32_mingw53
        # 额外设置msvc_arch
        include:
          - qt_arch: win64_msvc2017_64
            msvc_arch: x64
    # 步骤
    steps:
     - uses: actions/checkout@v1
       with:
          fetch-depth: 1
     - name: Install qt
       run: | 
        choco install qt5-default
     - name: build
       run: |
          C:\Qt\5.15.2\mingw81_64\bin\qmake.exe ..
          make.exe
