# windows.yml
name: Windows
env: 
   ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
on: 
  # push to trigger workflow
  push:
    # ignore README.md
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
  # pull_request时触发workflow
  pull_request:
    # ignore README.md
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
jobs:
  build:
    name: Build
    # windows-latest is windows server 2019
    runs-on: windows-latest
    strategy:
      matrix:
        qt_ver: [5.12.6]
        qt_target: [desktop]
        qt_arch: [win64_msvc2017_64]
        exclude: 
          - qt_ver: 5.9.8
            qt_arch: win32_msvc2017
        # set up msvc_arch
        include:
          - qt_arch: win64_msvc2017_64
            msvc_arch: x64
    steps:
      # install Qt
      - name: Install Qt
        # use external action for installing Qt
        uses: jurplel/install-qt-action@v3
        with:
          # Version of Qt to install
          version: ${{ matrix.qt_ver }}
          # Target platform for build
          target: ${{ matrix.qt_target }}
          # Architecture for Windows/Android
          arch: ${{ matrix.qt_arch }}
      # pull code
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Build something requiring CL.EXE
        uses: ilammy/msvc-dev-cmd@v1
      - uses: shogo82148/actions-setup-perl@v1
        with:
         perl-version: '5.32'
         distribution: strawberry
      - run: cpanm --installdeps .
      - run: prove -lv t
      # compile msvc
      - name: Make a Makefile and build application    
        shell: cmd
        env:
          vc_arch: ${{ matrix.msvc_arch }}
        run: |
          qmake
          perl -pi -e 's/^  */\t/' Makefile
          make       
